### ISSUE TITLE
Searchbar for general search 

### ISSUE THREAD

**Issue by lcryan** [lcryan/happyhour_application_lr#5]
**Goal:** 
User has to be able to search for cocktails by name or ingredient. 
User will be navigated to a list of results of a maximum of 5 cocktails or less. 
User can add 3 of those to his/her favourites list.

Steps to make the searchbar: 

- [x] create form and wrap it around the input 
- [x] onSubmitHandler - takes the value and navigates to the search page 
- [x] on the search page: query string output 
- [x] extract according API url including personal API token 
- [x] implement into async function to extract data - await axios.get etc. 
- [x] #15

**Comment by lcryan** [comment]
Finalized 

decided against making a different searchbar
