### ISSUE TITLE
Latest & Top Ten page - subpage & adding to favourites list 

### ISSUE THREAD

**Issue by lcryan** [lcryan/happyhour_application_lr#6]
**Goal:** 
User has to be able to view all cocktail and cocktail ingredients on an additional page - which he/she will be  navigated to (subpage)

**Steps to follow - things to think about** 

- [x] User has to be able to click on all cocktails - and then be navigated to that cocktail's subpage For this: make a navigate to subpage.
- [x] Each cocktail has to be individually displayed on page (for steps to follow: check on reddit example again - which you have worked on earlier this year). 
- [ ] User has to be able to choose a maximum of 3 cocktails from that list to his/her favourites list by ticking the checkboxes below each cocktail. if- else statement
- [ ] These will be saved to the favourites list by the system - a maximum of 10 cocktails can be saved by the user to that list.
- [ ] If the user wants to add more, the system will display an according error message and then send him/ her back to the overview list. if else statement 
- [ ] When successfully stored to favourites list: system will display a message for the user.

**Comment by lcryan** [comment]
This one was one of the requirements of the study assistant. I think they want me to practice these parts? I also don't really understand why this should be necessary; but as I said, I had to change it in my idea section
